### ISSUE TITLE
AttributeError: 'Variable' object has no attribute 'item' for ULMFiT_Classify.py

### ISSUE THREAD

**Issue by saket-maheshwary** [briandw/SiameseULMFiT#1]
I was able to execute the tokenization and pre-training scripts but for for ULMFiT_Classify i get the error --  AttributeError: 'Variable' object has no attribute 'item'. 

My pytorch version = 0.3.1

**Comment by briandw** [comment]
Thanks for trying out my code.

This is an issue with the Pytorch version. I'm using 0.4.1 and 0.3.1 doesn't have "item()". Please upgrade to the latest Pytorch as using item() will be required in 1.0. 

I'll reopen this issue if you still have trouble after upgrading.
